name: cpf
description: Biblioteca para manipulação de CPF.
version: 1.0.1
homepage: https://github.com/dartbrasil/cep
author: Rodrigo Muniz <rodrigo.temiski1995@gmail.com>

# As mentioned in Getting Ready for Dart 2
environment:
  sdk: '>=1.20.1 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.3.0
